### ISSUE TITLE
VPC Symmetry Error when running `cdk synthezize`

### ISSUE THREAD

**Issue by hrpomrx** [aws-samples/aws-cdk-sagemaker-studio#1]
[Error at /sagemakerStudioCDK] Could not find any VPCs matching {"account":"<redacted>","region":"us-east-1","filter":{"isDefault":"true"},"returnAsymmetricSubnets":true}
Found errors

**Comment by AmineIzanami** [comment]
For demo purpose, you need to have a default VPC in your AWS account, you can still replace explicitly with a VPC ID in sagemaker_studio_stack.py, if you do not have a default VPC set in yout AWS account.
`
default_vpc_id = ec2.Vpc.from_lookup(self, "VPC",
		                                       vpc_id = VPC_ID
		                                     )
`
