### ISSUE TITLE
Could not find any VPCs matching

### ISSUE THREAD

**Issue by yahavb** [aws-samples/aws-cdk-sagemaker-studio#2]
I followed the README and when I run `cdk synthesize` I got the error:
```
[Error at /sagemakerStudioCDK] Could not find any VPCs matching {"account":"nnnnnnnnnn","region":"us-west-2","filter":{"isDefault":"true"},"returnAsymmetricSubnets":true}

Found errors
```

I modified `app.py` with the right region. 

Is there a VPC I need to create before running this?

**Comment by AmineIzanami** [comment]
Reference to the [closed issue](https://github.com/aws-samples/aws-cdk-sagemaker-studio/issues/1)

But as it seems to be a recurrent issue, I'll update the code so that it takes a vpc_id from the CDK context rather than looking for the default VPC.
