### ISSUE TITLE
How to create Sagemaker studio project?

### ISSUE THREAD

**Issue by pratik5157** [aws-samples/aws-cdk-sagemaker-studio#3]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
I am trying to create sagemaker project following below steps:

create domain (using the example)
create user (using the example)
create jupyter app
create project 

Code for creating jupyter app:

`class SagemakerStudioJupyterAppConstruct(Construct):

    def __init__(self, scope: Construct,
                 construct_id: str, *,
                 app_name: str,
                 app_type: str,
                 domain_id: str,
                 user_profile_name: str,
                 depends_on=None, **kwargs) -> None:
        super().__init__(scope, construct_id)

        sagemaker_jupyter_app = sg.CfnApp(self, construct_id,
                                          app_name=app_name,
                                          app_type=app_type,
                                          domain_id=domain_id,
                                          user_profile_name=user_profile_name
                                          )
        sagemaker_jupyter_app.add_depends_on(depends_on_user_creation)`

Code for creating project:

`class SagemakerStudioProjectConstruct(Construct):

    def __init__(self, scope: Construct,
                 construct_id: str, *,
                 project_name: str,
                 project_description: str,
                 product_id: str,
                 depends_on=None,
                 **kwargs) -> None:
        super().__init__(scope, construct_id)

        sagemaker_studio_project = sg.CfnProject(self, construct_id,
                                                 project_name=project_name,
                                                 service_catalog_provisioning_details={
                                                     "ProductId": "prod-7tjedn5dz4jrw"
                                                 },
                                                 project_description=project_description
                                                 )`

Domain, user, jupyter app all gets created successfully. The problem comes in with project.
Below is the error :

`Resource handler returned message: "Product prod-7tjedn5dz4jrw does not exist or access was denied (Service: SageMaker, Status Code: 400, Request ID: 768116aa-e77b-4691-a972-38b83093fdc4)" (RequestToken: 45ca2a0c-3f03-e3e0-f29d-d9443ff4dfc1, HandlerErrorCode: GeneralServiceException)`

I am running this code from an ec2 instance that has SagemakerFullAccess
I also tried attaching SagemakerFullAccess execution role with project...but got the same error.

**Comment by AmineIzanami** [comment]
Based on the error, it seems that ProductId from the service catalog can not be reached in this case your EC2 instance needs permission to AWS Service Catalog

**Comment by pratik5157** [comment]
Issue resolved : 
https://stackoverflow.com/a/71982829/10214532
